### ISSUE TITLE
ScanNet.yaml

### ISSUE THREAD

**Issue by zjw102** [Zhimin-C/Bridge3D#2]
Hello author, in ScanNet.yaml your path is the path of the Shapenet dataset, whether it is a writing error.

**Comment by Zhimin-C** [comment]
Hi,

The code does not utilize the path specified in ScanNet.yaml for the data loader path. You can modify the local dataset path in Scannet.py within the /Pretrain/datasets/Scannet.py, specifically between lines 23 and 27.
