### ISSUE TITLE
python tag2text_SAM.py

### ISSUE THREAD

**Issue by zjw102** [Zhimin-C/Bridge3D#3]
Hello author, when I python tag2text_SAM.py, it shows missing parameters.
<img width="1127" alt="1718604704892" src="https://github.com/Zhimin-C/Bridge3D/assets/107674802/799e5ba8-44b0-4bb7-ba6a-d4119cc098e7">

So I'm looking at someone else's way and running it this way: python tag2text_SAM.py configs/Detic_LI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.py "/z_home/zjw/datasets/detic_centernet2_swin-b_fpn_4x_lvis-coco-in21k_20230120-0d301978.pth" .But：ModuleNotFoundError: No module named 'projects.Detic'

   So I went and downloaded someone else's Detic file again and ran it this way:python tag2text_SAM.py "/z_home/zjw/projects/Bridge3D-main/Preprocess/Detic/configs/detic_centernet2_swin-b_fpn_4x_lvis-coco-in21k.py" "/z_home/zjw/datasets/detic_centernet2_swin-b_fpn_4x_lvis-coco-in21k_20230120-0d301978.pth"
but:  requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased/tree/main?recursive=True&expand=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f58821ab130>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: 9c7584be-08d5-4839-b1a6-e61fb3d093a5)')

so How the hell am I going to run tag2text_SAM.py

**Comment by Zhimin-C** [comment]
I have updated the readme in the preprocess. Now you can have a try.

**Comment by zjw102** [comment]
Thank you for your reply, the issue has been solved!
