### ISSUE TITLE
S3DIS

### ISSUE THREAD

**Issue by zjw102** [Zhimin-C/Bridge3D#5]
Hello author, I would like to know where the experiment is in Table 2: 3D semantic segmentation results on S3DIS dataset. in the article, and how can I implement this part, I look forward to your reply!

**Comment by zjw102** [comment]
Looking forward to your reply

**Comment by Zhimin-C** [comment]
Apologies for the delayed response. Since the semantic segmentation results did not achieve state-of-the-art performance, we have not included them for now. I will organize the code and upload it once I have more time.

**Comment by zjw102** [comment]
> Apologies for the delayed response. Since the semantic segmentation results did not achieve state-of-the-art performance, we have not included them for now. I will organize the code and upload it once I have more time.

Is it organized? I really need it, thank you

**Comment by zjw102** [comment]
> Apologies for the delayed response. Since the semantic segmentation results did not achieve state-of-the-art performance, we have not included them for now. I will organize the code and upload it once I have more time.

Even if the result doesn't achieve state-of-the-art performance, it's not important. I just want to know how to implement it. I'm really looking forward to your response
