### ISSUE TITLE
Question about training setting

### ISSUE THREAD

**Issue by linQian99** [Zhimin-C/Bridge3D#7]
Thank you for your great work! May I ask the hardware requirement to fine tune? Thank you

**Comment by Zhimin-C** [comment]
We fine-tuned the model based on the baseline method, such as 3DETR. Please refer to their GitHub page for the specific requirements. I believe a single 3090 GPU should be sufficient

**Comment by linQian99** [comment]
Thank you for your reply! May I ask for training the Bridge3D Pre-training how many GPUs do I need? Sorry to bother you again. Thank you for your help!

**Comment by Zhimin-C** [comment]
I utilize 2xA100 for pre-training. You can try utilize 2x4090 or reduce batch size if memory is not enough.

**Comment by linQian99** [comment]
Thank you for your rapid response once again! I will try it

**Comment by linQian99** [comment]
Sorry to bother again, may I ask how long time does pre-traing take for 2 A100?

**Comment by Zhimin-C** [comment]
Around 1 day maybe.
